language: java
jdk:
  - "openjdk7"
# Not yet available
#  - "openjdk8"
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
# command to install dependencies
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq ruby ruby-cassiopee gawk swi-prolog junit4 ant ant-optional libncursesw5-dev texlive texlive-latex-extra tex4ht"
  - "sudo add-apt-repository ppa:olivier-sallou/cassiopee-ubuntu -y"
  - "sudo apt-get update -qq"
  - "sudo apt-get install cassiopee"
  - "mkdir test/tmp"
  - "mkdir test/results"


# command to run tests
script: ant dist_swi
