addons:
  hosts:
     - logolhost
  hostname: logolhost
language: java
jdk:
  - "openjdk7"
# Not yet available
#  - "openjdk8"
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
# command to install dependencies
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq ruby ruby-cassiopee gawk swi-prolog junit4 ant ant-optional libncursesw5-dev texlive texlive-latex-extra tex4ht cassiopee"
  - "sudo add-apt-repository ppa:olivier-sallou/cassiopee-ubuntu -y" # cassiopee not in Ubuntu Precise used by Travis, use PPA
  - "sudo apt-get update -qq"
  - "sudo apt-get install cassiopee"
  - "mkdir test/tmp"
  - "mkdir test/results"
#- sudo hostname "$(hostname | cut -c1-63)" # Fix for Travis-CI raising Java overflow on hostname, https://github.com/travis-ci/travis-ci/issues/5227
#- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
#- cat /etc/hosts # Check hosts content after modification


# command to run tests
script: ant test_swi
