language: java
jdk:
  - "openjdk7"
  - "openjdk8"
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
# command to install dependencies
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq ruby cassiopee ruby-cassiopee gawk swi-prolog junit4 ant ant-optional libncursesw5-dev texlive texlive-latex-extra tex4ht"

# command to run tests
script: ant dist_swi
